### ISSUE TITLE
Attempt to use map which was not loaded: world_mill

### ISSUE THREAD

**Issue by reins-ch** [alex-pex/jvectormap#1]
I just installed this library (I have used jvectorMap in non-node.js projects) and I get the following error:
`Attempt to use map which was not loaded: world_mill`.

My code:
``` javascript
const $ = require("jquery");
require("jvectormap-next")($);

$("#map").vectorMap({
  map: "world_mill",
  backgroundColor: "#c6ecff",
  zoomMax: 25
});
```

The readme doesn't say that I should import anything else. In my other projects (non-node) I had to load a script that contained this map but I don't see where it is in your repo.

Thanks in advance for the help!

**Comment by alex-pex** [comment]
Hi!

This package is the spiritual successor of the _not maintained anymore_ package jvectormap. For most parts, you can rely on the official documentation : https://jvectormap.com/tutorials/getting-started/

It's not stated in the doc, but you should also import the map you want to use, eg: https://jvectormap.com/js/jquery-jvectormap-world-mill.js

I will very soon make a lot of change on how packages are built and exposed (maybe copying map content into the repository), and I will enhance the documentation with demos

**Comment by alex-pex** [comment]
I merged the monorepo branch, which brings a better documentation : http://alex-pex.github.io/jvectormap/ and I need to publish updated packages.

I hope this will help :)

**Comment by alex-pex** [comment]
New versions are published!
