### ISSUE TITLE
useRef on react-vectormap?

### ISSUE THREAD

**Issue by ikbalmoh** [alex-pex/jvectormap#3]
Hello Alex, 
Can we use the useRef hook on CustomVectorMap?

What I want to achieve is to setFocus programmatically by clicking a region.

**Comment by alex-pex** [comment]
Hello!

Internally I have a map ref, but it isn't exposed. I could expose this for sure. But there is an alternative : you can focus on elements declaratively using the "focusOn" prop

```jsx
<VectorMap focusOn="alabama" />
```
or
```jsx
<VectorMap focusOn={{ region: "alabama" }} />
```

It has the same behavior has https://jvectormap.com/documentation/javascript-api/jvm-map/#focusOn
